add continue as an application
stanford-crfm/ecosystem-graphs pull request #140
Opened 2023-10-26 18:10 UTC by TyDunn

I would like to add Continue as an application to this list. Thanks for your time and consideration!

2023-11-09 04:32 UTC, jxue16 requested changes

2023-11-09 04:32 UTC, jxue16 commented on assets/continue.yaml
Could rename organization to Continue Dev to reduce ambiguity, otherwise looks good!

2023-11-10 01:24 UTC, TyDunn commented on assets/continue.yaml
> +  organization: Continue
```suggestion
  organization: Continue Dev, Inc.
```

2023-11-10 01:24 UTC, TyDunn commented on assets/continue.yaml
I made the change. Thanks!

2023-11-10 03:35 UTC, jxue16 approved these changes

2023-11-21 00:50 UTC, merged